default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: imagebook_development
test:
  <<: *default
  database: imagebook_test

production:
  <<: *default
  database: imagebook_production
  username: imagebook
  password: <%= ENV['IMAGEBOOK_DATABASE_PASSWORD'] %>
